OPENAI_API_KEY = "your-api-key"
OPENAI_EMBEDDING_MODEL = "text-embedding-3-small"
OPENAI_API_BASE = "https://api.openai.com/v1"


PG_HOST = "your.supabase.host"
PG_PORT = "5432"
PG_USER = "postgres"
PG_PASSWORD = "10053205"
PG_DB = "postgres"